const fs = require('fs');
const path = require('path');

const VOLUMES_DIR = path.join(__dirname, '../data/volumes');
const CARDS_FILE = path.join(__dirname, '../data/cards.json');
const MANIFEST_FILE = path.join(__dirname, '../data/manifest.json');

console.log('🔄 Compilando mazo Hit-Tazos Tech desde volúmenes...');

if (!fs.existsSync(VOLUMES_DIR)) {
  console.error(`❌ Error: No se encontró el directorio ${VOLUMES_DIR}`);
  process.exit(1);
}

const files = fs.readdirSync(VOLUMES_DIR).filter(f => f.endsWith('.json'));
files.sort(); // vol0, vol1...

let allCards = [];

for (const file of files) {
  const filePath = path.join(VOLUMES_DIR, file);
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  allCards = allCards.concat(data);
}

if (allCards.length !== 576) {
  console.error(`❌ Error de validación: Se esperaban 576 cartas, pero hay ${allCards.length}.`);
  process.exit(1);
}

// Generate compiled output
fs.writeFileSync(CARDS_FILE, JSON.stringify(allCards, null, 2), 'utf8');

let appVersion = '1.0.0-rc4';
try {
  appVersion = fs.readFileSync(path.join(__dirname, '../VERSION'), 'utf8').trim();
} catch (_) {}

const catalogFile = path.join(__dirname, '../data/catalog.json');
let catalogVolumes = {};
if (fs.existsSync(catalogFile)) {
  try {
    catalogVolumes = JSON.parse(fs.readFileSync(catalogFile, 'utf8')).volumes || {};
  } catch (_) {}
}

const volumeList = files.map((file, idx) => {
  const filePath = path.join(VOLUMES_DIR, file);
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  const slug = file.replace(/^vol\d+_/, '').replace('.json', '');
  const title = catalogVolumes[slug] || slug;
  const cardsCount = data.length;
  const pagesCarta = Math.ceil(cardsCount / 6) * 2;
  return {
    id: `vol${idx}`,
    slug,
    title,
    cardsCount,
    pagesCarta,
    pdfFilename: `hit-tazos-tech-vol${idx}-${slug}.pdf`,
    pdfPath: `/assets/print/hit-tazos-tech-vol${idx}-${slug}.pdf`
  };
});

// Generate manifest
const manifest = {
  compiledAt: new Date().toISOString(),
  totalCards: allCards.length,
  version: appVersion,
  volumesCount: files.length,
  volumes: volumeList
};

fs.writeFileSync(MANIFEST_FILE, JSON.stringify(manifest, null, 2), 'utf8');

// Generar bundle local web/deck-data.js para soporte 100% offline y protocolo file://
try {
  const DECK_DATA_FILE = path.join(__dirname, '../web/deck-data.js');
  const cardColorsFile = path.join(__dirname, '../data/card_colors.json');
  const cardColors = fs.existsSync(cardColorsFile) ? JSON.parse(fs.readFileSync(cardColorsFile, 'utf8')) : null;
  const catalog = fs.existsSync(catalogFile) ? JSON.parse(fs.readFileSync(catalogFile, 'utf8')) : null;
  const deckBundle = `// Autogenerated by scripts/build_cards.js - Zero-config offline & file:// protocol support\nwindow.HIT_DECK_DATA = {\n  version: ${JSON.stringify(appVersion)},\n  cards: ${JSON.stringify(allCards)},\n  cardColors: ${JSON.stringify(cardColors)},\n  catalog: ${JSON.stringify(catalog)},\n  manifest: ${JSON.stringify(manifest)}\n};\n`;
  fs.writeFileSync(DECK_DATA_FILE, deckBundle, 'utf8');
  console.log(`📦 Bundle offline generado en: ${DECK_DATA_FILE}`);
} catch (e) {
  console.warn('⚠️ No se pudo generar web/deck-data.js:', e.message);
}

console.log(`✅ ${allCards.length} tarjetas compiladas exitosamente en: ${CARDS_FILE}`);
console.log(`📋 Manifiesto oficial generado en: ${MANIFEST_FILE}`);
console.log('🎉 Compilación completada con éxito.');
